# 연습 문제

In [20]:
# 1.
vector = np.zeros((10, ), int)
vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# 2.
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [23]:
# 3.
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [28]:
# 4.
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [31]:
# 5.
a = np.arange(0, 9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# 6.
vector = np.array([1,2,0,0,4,0], int)
condition = vector != 0
vector[condition]

array([1, 2, 4])

In [33]:
# 7.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# 8.
matrix_array = np.random.randn(3, 3)
matrix_array

array([[-1.55210612, -0.14768641, -1.07886334],
       [ 1.6479487 ,  0.26600808, -0.25628584],
       [-0.9013787 , -0.32783574, -0.13268342]])

In [59]:
# 8. 풀이
np.random.seed(604)
a = np.random.random(9).reshape(3, 3)
a

array([[0.29199497, 0.16131679, 0.6353873 ],
       [0.17588539, 0.10216827, 0.59007575],
       [0.79085085, 0.97099855, 0.31192678]])

In [53]:
# 9.
print(matrix_array.max())
print(matrix_array.min())

1.647948698800651
-1.552106123591786


In [55]:
# 10.
print(np.mean(matrix_array, axis=1))
print(np.mean(matrix_array, axis=0))

[-0.92621862  0.55255698 -0.45396596]
[-0.26851204 -0.06983802 -0.48927754]
